Update sniffing instructions
Bambu-Research-Group/RFID-Tag-Guide pull request #24
Opened 2024-05-21 12:11 UTC by queengooborg

This performs a number of updates to the sniffing instructions for grammar fixes, a better explanation of where to place the Proxmark3 for sniffing, fixed commands and a link to the Proxmark3 software.

2024-05-22 01:40 UTC, thekakester commented on README.md
> +   - Run `hf mf dump -k [path-to-dumpfile]` to dump the contents of the tag using the 16 keys we discovered
```suggestion
11. **Dump RFID Contents**
   - Run `hf mf dump -k [path-to-keyfile]` to dump the contents of the tag using the 16 keys we discovered
```

2024-05-22 01:40 UTC, thekakester commented on README.md
> +      - macOS (ARM) Eample: `cd /opt/homebrew/Cellar/proxmark3/4.17768/share/proxmark3/`
This was done on an M2 Mac, so it wasn't intel.  I guess we just used two different brew install locations

2024-05-22 01:44 UTC, thekakester requested changes
Firstly, thanks for reading over everything and recommending changes.  I appreciate the extra set of eyes, and making the document look more professional, as well as validating that the instructions actually work.

The only thing that stood out to me was Intel vs ARM, but these instructions were written for an M2 Mac.  We should definitely not list "Intel" there.  We can probably keep just one of those examples, and add a note that install locations will vary from machine to machine.

The only other comment was an argument for a KEYfile instead of DUMPfile.

If you can touch these up, I'll merge in the PR.

2024-05-22 02:11 UTC, queengooborg commented on README.md
> +      - macOS (ARM) Eample: `cd /opt/homebrew/Cellar/proxmark3/4.17768/share/proxmark3/`
That's...odd that the cellar would be in `/usr/local` on an M2 Mac.  The default install path for Homebrew is `/usr/local` on Intel-based macOS installations, and `/opt/homebrew` for Apple Silicon.

Since this is a CD command, though, we could simplify this greatly and take advantage of the `brew --prefix` command!  In other words, we can do this:

```md
- macOS/Linux: `cd $(brew --prefix proxmark3)/share/proxmark3/`
- Windows: TBD
```

Does that sound good?

2024-05-22 02:12 UTC, queengooborg commented on README.md
> +   - Run `hf mf dump -k [path-to-dumpfile]` to dump the contents of the tag using the 16 keys we discovered
Ah, thanks, great catch!  Couldn't commit the suggestion directly for some reason, so just pushed a new commit!

2024-05-23 16:41 UTC, thekakester approved these changes

2024-05-23 16:42 UTC, merged