Update extractor to allow env variable-defined Proxmark3 path
Bambu-Research-Group/RFID-Tag-Guide pull request #26
Opened 2024-05-28 13:00 UTC by queengooborg

This PR updates the new `traceKeyExtractor.py` script to remove the need to modify the script file to specify the installation path of Proxmark3, both by leveraging Homebrew directly to find the install path (avoiding cross-platform and cross-architecture issues) and adding the ability to use an environment variable to specify the installation directory.

Additionally, this adds a `.gitignore` to ignore any dictionary files generated by the script.

2024-05-29 00:35 UTC, queengooborg commented
> Could be that we're running different python versions

That would make a lot of sense -- what version of Python are you running if I may ask?  I'm running Python 3.12.3 personally!

2024-05-29 05:54 UTC, queengooborg commented on traceKeyExtractor.py
>          print(f"Viewing tracelog with {len(keyList)} discovered keys")
Ah, this seemed to have been a bug due to a bad logic gate because the `pm3Location` variable was set to an empty string, but a check was in place to see if it was `None` instead.  Since it wasn't, the program thought that everything was fine and moved along.  This has now been fixed!

2024-09-29 00:24 UTC, Aptimex commented on traceKeyExtractor.py
> +        print(f"pm3 {" ".join(cmd_list[1:])}")
```suggestion
        print(f"pm3 {' '.join(cmd_list[1:])}")
```
Fixes syntax error when double quotes are used inside double quotes.

2024-09-29 00:24 UTC, Aptimex commented on traceKeyExtractor.py
> +    print(f"tools/mf_nonce_brute {" ".join(cmd_list[1:])}")
```suggestion
    print(f"tools/mf_nonce_brute {' '.join(cmd_list[1:])}")
```
Fixes syntax error when double quotes are used inside double quotes.

2024-09-29 00:25 UTC, Aptimex requested changes
Fixes for syntax error when double quotes are used inside double quotes.

2024-11-19 15:41 UTC, thekakester approved these changes
Approved.  I took too long to review this, so a bit of it is outdated still

2024-11-19 15:42 UTC, thekakester commented
Merged trace key extractor updates + documentation

2024-11-19 15:42 UTC, merged