Added consortium documentation
Bambu-Research-Group/RFID-Tag-Guide pull request #58
Opened 2024-12-17 16:16 UTC by thekakester

Renamed to OpenTag
Cleaned up formatting and redundant documentation
Grouped all the specifications (hardware, mechanical, data, and web) into one group

2024-12-17 17:33 UTC, spuder approved these changes

2024-12-17 17:51 UTC, spuder commented
File name is still `OpenSourceRFID.md`. Keep that the same? or rename it?

2024-12-17 19:09 UTC, trentrand commented on OpenSourceRfid.md
> +NFC NTAG216: 13.56mhz 888-byte
Happy to see this decision!

2024-12-17 23:21 UTC, queengooborg requested changes
Couple of proofreading points, but LGTM otherwise!  Getting super excited to see the standard developing further!

2024-12-17 23:21 UTC, queengooborg commented on OpenSourceRfid.md
> +NTAG216 tags are cheap, common, and allow 888 bytes of data, which is plenty of space to store required information. NFC tags such as NTAG216 can be read/written with android smartphones. 13.56mhz RF
```suggestion
NTAG216 tags are cheap, common, and allow 888 bytes of data, which is plenty of space to store required information. NFC tags such as NTAG216 can be read/written with smartphones. 13.56mhz RFID modules are plentiful, low-cost and Arduino-compatible, allowing for easy integration.
```

2024-12-17 23:21 UTC, queengooborg commented on OpenSourceRfid.md
> +* The tag should never be more than 4.0mm away from the external surface of the spool. For spool sides thicker than 4mm,there must be a cutout to embed the tag, or the tag should be fixed to the outs
```suggestion
* The tag should never be more than 4.0mm away from the external surface of the spool
  * For spool sides thicker than 4mm, there must be a cutout to embed the tag, or the tag should be fixed to the outside of the spool
```

2024-12-17 23:21 UTC, queengooborg commented on OpenSourceRfid.md
> +* Two tags should be used, one on each end of the spool, directly across from eachother
```suggestion
* Two tags should be used, one on each end of the spool, directly across from each other
```

2024-12-17 23:21 UTC, queengooborg commented on OpenSourceRfid.md
> +These complex variables can be looked up using the "web api" url that is on the RFID tag.
```suggestion
These complex variables can be looked up using the "web API" URL that is stored on the RFID tag.
```

2024-12-17 23:21 UTC, queengooborg commented on OpenSourceRfid.md
> +The format of this data should be JSON
```suggestion
The format of this data should be JSON.
```

2024-12-17 23:21 UTC, queengooborg commented on OpenSourceRfid.md
> +    * Tags only have 888 bytes of memory, which would be eaten up quickly
```suggestion
    * NTAG216 tags only have 888 bytes of memory, which would be eaten up quickly
```

2024-12-17 23:21 UTC, queengooborg commented on OpenSourceRfid.md
> +    * Lookup tables can become out of date, which would require regular "firmware updates" to devices that read tags to make sure they've downloaded the most recent table.
```suggestion
    * Lookup tables can quickly become outdated, which would require regular updates to tag readers to make sure they've downloaded the most recent table.
```

2024-12-17 23:26 UTC, joaoachando reviewed
Nit💄

2024-12-17 23:26 UTC, joaoachando commented on OpenSourceRfid.md
> +RFID is becoming more prevalent, with each company launching their own RFID system that is incompatible with the rest.
```suggestion
RFID is becoming more prevalent, with each company launching its own RFID system that is incompatible with the rest.
```

2024-12-17 23:26 UTC, joaoachando commented on OpenSourceRfid.md
> +NTAG216 tags are cheap, common, and allow 888 bytes of data, which is plenty of space to store required information. NFC tags such as NTAG216 can be read/written with android smartphones. 13.56mhz RF
```suggestion
NTAG216 tags are cheap and common. They allow 888 bytes of data, which is plenty of space to store required information. NFC tags such as NTAG216 can be read/written with Android smartphones. 13.56mhz RFID modules are plentiful and low-cost, and they are Arduino-compatible, allowing new projects to be spun up.
```

2024-12-17 23:26 UTC, joaoachando commented on OpenSourceRfid.md
> +* Two tags should be used, one on each end of the spool, directly across from eachother
```suggestion
* Tag placement: The center should be 56.0mm away from the center of the spool (see pic)
* The tag should never be more than 4.0mm away from the external surface of the spool. For spool sides thicker than 4mm, there must be a cutout to embed the tag, or the tag should be fixed to the outside of the spool
* Two tags should be used, one on each end of the spool, directly across from each other
```

2024-12-17 23:26 UTC, joaoachando commented on OpenSourceRfid.md
> +The exact contents of this data is still open to discussion, and it is not required to launch the OpenTag standard.  The web API can be implemented in the future without affecting the launch of OpenT
```suggestion
The exact contents of this data are still open to discussion, and it is not required to launch the OpenTag standard.  The web API can be implemented in the future without affecting the launch of OpenTag. 
```

2024-12-17 23:26 UTC, joaoachando commented on OpenSourceRfid.md
> +    * MIFARE uses about 25% of memory to encrypt data, preventing read/write operations, which is not applicable for OpenTag because of the open source nature
```suggestion
* NTAG216 vs MIFARE:
    * NTAG216 is compatible with smartphones and has slightly more usable memory than MIFARE tags
    * MIFARE uses about 25% of memory to encrypt data, preventing read/write operations, which is not applicable for OpenTag because of the open-source nature
```

2024-12-17 23:26 UTC, joaoachando commented on OpenSourceRfid.md
> +    * Tags only have 888 bytes of memory, which would be eaten up quickly
```suggestion
* JSON vs Memory Map:
    * Formats such as JSON (human-readable text) take up considerably more memory than memory mapped.  For example, defining something like Printing Temperature would be `PrintTemp:225` which is 13 bytes, versus storing a memory-mapped 2-byte number.  Tokens could be reduced, but that also defeats the purpose of using JSON in the first place, which is often for readability.
    * Tags only have 888 bytes of memory, which would be eaten up quickly
```

2024-12-17 23:26 UTC, joaoachando commented on OpenSourceRfid.md
> +    * On-demand lookup (via internet) would require someone host a database. Hosting this data would have costs associated with it, and would also put the control of the entire OpenTag format in the
```suggestion
    * On-demand lookup (via the internet) would require someone to host a database. Hosting this data would have costs associated with it, and would also put the control of the entire OpenTag format in the hands of a single person/company
```

2024-12-18 01:50 UTC, queengooborg commented on OpenSourceRfid.md
> +NTAG216 tags are cheap, common, and allow 888 bytes of data, which is plenty of space to store required information. NFC tags such as NTAG216 can be read/written with android smartphones. 13.56mhz RF
I am now realizing that these lines weren't actually added, but the Git diff made it seem like they were...whoops!

Drive-by fixes then?  XP

2024-12-18 22:22 UTC, fmauNeko commented on OpenSourceRfid.md
> +NFC NTAG216: 13.56mhz 888-byte
```suggestion
NFC NTAG216: 13.56 MHz 888-byte tags
```

2024-12-18 22:22 UTC, fmauNeko commented on OpenSourceRfid.md
> +NTAG216 tags are cheap, common, and allow 888 bytes of data, which is plenty of space to store required information. NFC tags such as NTAG216 can be read/written with android smartphones. 13.56mhz RF
```suggestion
NTAG216 tags are cheap, common, and allow 888 bytes of data, which is plenty of space to store required information. NFC tags such as NTAG216 can be read/written with Android smartphones. 13.56 MHz RFID modules are plentiful and low-cost and are arduino-compatible to allow for new projects to be spun up.
```

2024-12-18 22:22 UTC, fmauNeko commented on OpenSourceRfid.md
> +NFC NTAG216 was chosen over MIFARE 1K Classic tags, which is what the Bambu AMS uses.  NTAG216 was chosen over MIFARE 1K for the following reasons:
```suggestion
NFC NTAG216 was chosen over MIFARE 1K Classic tags, which is what the Bambu AMS uses, for the following reasons:
```

2024-12-18 22:22 UTC, fmauNeko commented on OpenSourceRfid.md
> +NTAG216 tags have 888 bytes of total memory.
```suggestion
NTAG216 tags have 888 bytes of usable memory.
```

NTAG216 actually got 924 bytes, of which 888 is usable

2025-01-28 20:25 UTC, queengooborg approved these changes

2025-01-28 20:25 UTC, merged